	.align 2
DirectSoundWaveData_sc88_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88_organ2::
	.incbin "sound/direct_sound_samples/sc88_organ2.bin"

	.align 2
DirectSoundWaveData_sc88_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88_fretless_bass.bin"

	.align 2
DirectSoundWaveData_jv1080_slap_bass::
	.incbin "sound/direct_sound_samples/jv1080_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88_synth_bass::
	.incbin "sound/direct_sound_samples/sc88_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88_timpani::
	.incbin "sound/direct_sound_samples/sc88_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_electric_guitar::
	.incbin "sound/direct_sound_samples/unused_electric_guitar.bin"

	.align 2
DirectSoundWaveData_unused_sc88_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_low::
	.incbin "sound/direct_sound_samples/unknown_wood_block_low.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_high::
	.incbin "sound/direct_sound_samples/unknown_wood_block_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_kick::
	.incbin "sound/direct_sound_samples/sc88_standard_kick.bin"

	.align 2
DirectSoundWaveData_sc88_standard3_snare::
	.incbin "sound/direct_sound_samples/sc88_standard3_snare.bin"

	.align 2
DirectSoundWaveData_sc88_standard_hand_clap::
	.incbin "sound/direct_sound_samples/sc88_standard_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unknown_tom::
	.incbin "sound/direct_sound_samples/unknown_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_unknown_tambourine::
	.incbin "sound/direct_sound_samples/unknown_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_bongo::
	.incbin "sound/direct_sound_samples/sc88_bongo.bin"

	.align 2
DirectSoundWaveData_sc88_bongo_low::
	.incbin "sound/direct_sound_samples/sc88_bongo_low.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_unknown_cowbell::
	.incbin "sound/direct_sound_samples/unknown_cowbell.bin"

	.align 2
DirectSoundWaveData_unknown_djembe::
	.incbin "sound/direct_sound_samples/unknown_djembe.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_high::
	.incbin "sound/direct_sound_samples/unknown_anvil_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_bells::
	.incbin "sound/direct_sound_samples/sc88_standard_bells.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_low::
	.incbin "sound/direct_sound_samples/unknown_anvil_low.bin"

	.align 2
DirectSoundWaveData_unknown_ethnic_drum::
	.incbin "sound/direct_sound_samples/unknown_ethnic_drum.bin"

	.align 2
DirectSoundWaveData_unknown_tsuzumi::
	.incbin "sound/direct_sound_samples/unknown_tsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_48::
	.incbin "sound/direct_sound_samples/sc88_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_60::
	.incbin "sound/direct_sound_samples/sc88_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_72::
	.incbin "sound/direct_sound_samples/sc88_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_84::
	.incbin "sound/direct_sound_samples/sc88_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88_trumpet_84.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_39::
	.incbin "sound/direct_sound_samples/unknown_trombone_39.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_51::
	.incbin "sound/direct_sound_samples/unknown_trombone_51.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88_flute::
	.incbin "sound/direct_sound_samples/sc88_flute.bin"

	.align 2
DirectSoundWaveData_sc88_pick_bass::
	.incbin "sound/direct_sound_samples/sc88_pick_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_unknown_church_organ::
	.incbin "sound/direct_sound_samples/unknown_church_organ.bin"

	.align 2
DirectSoundWaveData_emu_ii_pipe_organ::
	.incbin "sound/direct_sound_samples/emu_ii_pipe_organ.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88_square_wave::
	.incbin "sound/direct_sound_samples/sc88_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88_wind::
	.incbin "sound/direct_sound_samples/sc88_wind.bin"

	.align 2
DirectSoundWaveData_sc88_bubbles::
	.incbin "sound/direct_sound_samples/sc88_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_unused_acid_bass::
	.incbin "sound/direct_sound_samples/unused_acid_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_unknown_polysynth::
	.incbin "sound/direct_sound_samples/unknown_polysynth.bin"

	.align 2
DirectSoundWaveData_sc88_harp::
	.incbin "sound/direct_sound_samples/sc88_harp.bin"

	.align 2
DirectSoundWaveData_sc88_xylophone::
	.incbin "sound/direct_sound_samples/sc88_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88_accordion::
	.incbin "sound/direct_sound_samples/sc88_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Chapebaya::
	.incbin "sound/direct_sound_samples/cry_chapebaya.bin"

	.align 2
Cry_Denpecha::
	.incbin "sound/direct_sound_samples/cry_denpecha.bin"

	.align 2
Cry_Denfrota::
	.incbin "sound/direct_sound_samples/cry_denfrota.bin"

	.align 2
Cry_Coalchu::
	.incbin "sound/direct_sound_samples/cry_coalchu.bin"

	.align 2
Cry_Rallama::
	.incbin "sound/direct_sound_samples/cry_rallama.bin"

	.align 2
Cry_Roellama::
	.incbin "sound/direct_sound_samples/cry_roellama.bin"

	.align 2
Cry_Todad::
	.incbin "sound/direct_sound_samples/cry_todad.bin"

	.align 2
Cry_Shroad::
	.incbin "sound/direct_sound_samples/cry_shroad.bin"

	.align 2
Cry_Bultoad::
	.incbin "sound/direct_sound_samples/cry_bultoad.bin"

	.align 2
Cry_Larvet::
	.incbin "sound/direct_sound_samples/cry_larvet.bin"

	.align 2
Cry_Morfade::
	.incbin "sound/direct_sound_samples/cry_morfade.bin"

	.align 2
Cry_Eyefly::
	.incbin "sound/direct_sound_samples/cry_eyefly.bin"

	.align 2
Cry_Drosofly::
	.incbin "sound/direct_sound_samples/cry_drosofly.bin"

	.align 2
Cry_Metagaster::
	.incbin "sound/direct_sound_samples/cry_metagaster.bin"

	.align 2
Cry_Phylafly::
	.incbin "sound/direct_sound_samples/cry_phylafly.bin"

	.align 2
Cry_Ornlil::
	.incbin "sound/direct_sound_samples/cry_ornlil.bin"

	.align 2
Cry_Wasoo::
	.incbin "sound/direct_sound_samples/cry_wasoo.bin"

	.align 2
Cry_Volateo::
	.incbin "sound/direct_sound_samples/cry_volateo.bin"

	.align 2
Cry_Batoka::
	.incbin "sound/direct_sound_samples/cry_batoka.bin"

	.align 2
Cry_Mouspid::
	.incbin "sound/direct_sound_samples/cry_mouspid.bin"

	.align 2
Cry_Turkur::
	.incbin "sound/direct_sound_samples/cry_turkur.bin"

	.align 2
Cry_Peakur::
	.incbin "sound/direct_sound_samples/cry_peakur.bin"

	.align 2
Cry_ChukTxu::
	.incbin "sound/direct_sound_samples/cry_chuk_txu.bin"

	.align 2
Cry_Leeckey::
	.incbin "sound/direct_sound_samples/cry_leeckey.bin"

	.align 2
Cry_Covolts::
	.incbin "sound/direct_sound_samples/cry_covolts.bin"

	.align 2
Cry_Lucivolts::
	.incbin "sound/direct_sound_samples/cry_lucivolts.bin"

	.align 2
Cry_Nole::
	.incbin "sound/direct_sound_samples/cry_nole.bin"

	.align 2
Cry_Groundoe::
	.incbin "sound/direct_sound_samples/cry_groundoe.bin"

	.align 2
Cry_Urtiga::
	.incbin "sound/direct_sound_samples/cry_urtiga.bin"

	.align 2
Cry_Urtigere::
	.incbin "sound/direct_sound_samples/cry_urtigere.bin"

	.align 2
Cry_Venogena::
	.incbin "sound/direct_sound_samples/cry_venogena.bin"

	.align 2
Cry_Urtigo::
	.incbin "sound/direct_sound_samples/cry_urtigo.bin"

	.align 2
Cry_Urtigoro::
	.incbin "sound/direct_sound_samples/cry_urtigoro.bin"

	.align 2
Cry_Venogeno::
	.incbin "sound/direct_sound_samples/cry_venogeno.bin"

	.align 2
Cry_Amairi::
	.incbin "sound/direct_sound_samples/cry_amairi.bin"

	.align 2
Cry_Ograiri::
	.incbin "sound/direct_sound_samples/cry_ograiri.bin"

	.align 2
Cry_Hormig::
	.incbin "sound/direct_sound_samples/cry_hormig.bin"

	.align 2
Cry_Llamose::
	.incbin "sound/direct_sound_samples/cry_llamose.bin"

	.align 2
Cry_Fatte::
	.incbin "sound/direct_sound_samples/cry_fatte.bin"

	.align 2
Cry_Glotten::
	.incbin "sound/direct_sound_samples/cry_glotten.bin"

	.align 2
Cry_Stulo::
	.incbin "sound/direct_sound_samples/cry_stulo.bin"

	.align 2
Cry_Fungio::
	.incbin "sound/direct_sound_samples/cry_fungio.bin"

	.align 2
Cry_Semilleto::
	.incbin "sound/direct_sound_samples/cry_semilleto.bin"

	.align 2
Cry_Flocepan::
	.incbin "sound/direct_sound_samples/cry_flocepan.bin"

	.align 2
Cry_Arquidea::
	.incbin "sound/direct_sound_samples/cry_arquidea.bin"

	.align 2
Cry_Streek::
	.incbin "sound/direct_sound_samples/cry_streek.bin"

	.align 2
Cry_Loggre::
	.incbin "sound/direct_sound_samples/cry_loggre.bin"

	.align 2
Cry_Capritle::
	.incbin "sound/direct_sound_samples/cry_capritle.bin"

	.align 2
Cry_Deeretle::
	.incbin "sound/direct_sound_samples/cry_deeretle.bin"

	.align 2
Cry_Armorito::
	.incbin "sound/direct_sound_samples/cry_armorito.bin"

	.align 2
Cry_Armorazo::
	.incbin "sound/direct_sound_samples/cry_armorazo.bin"

	.align 2
Cry_Ankori::
	.incbin "sound/direct_sound_samples/cry_ankori.bin"

	.align 2
Cry_Fureep::
	.incbin "sound/direct_sound_samples/cry_fureep.bin"

	.align 2
Cry_Pulsul::
	.incbin "sound/direct_sound_samples/cry_pulsul.bin"

	.align 2
Cry_Koropul::
	.incbin "sound/direct_sound_samples/cry_koropul.bin"

	.align 2
Cry_Darkoon::
	.incbin "sound/direct_sound_samples/cry_darkoon.bin"

	.align 2
Cry_Huntoon::
	.incbin "sound/direct_sound_samples/cry_huntoon.bin"

	.align 2
Cry_Tikika::
	.incbin "sound/direct_sound_samples/cry_tikika.bin"

	.align 2
Cry_Tikiriki::
	.incbin "sound/direct_sound_samples/cry_tikiriki.bin"

	.align 2
Cry_Poocher::
	.incbin "sound/direct_sound_samples/cry_poocher.bin"

	.align 2
Cry_Wappy::
	.incbin "sound/direct_sound_samples/cry_wappy.bin"

	.align 2
Cry_Riwoof::
	.incbin "sound/direct_sound_samples/cry_riwoof.bin"

	.align 2
Cry_Ivoro::
	.incbin "sound/direct_sound_samples/cry_ivoro.bin"

	.align 2
Cry_Dreamo::
	.incbin "sound/direct_sound_samples/cry_dreamo.bin"

	.align 2
Cry_Mammare::
	.incbin "sound/direct_sound_samples/cry_mammare.bin"

	.align 2
Cry_Kango::
	.incbin "sound/direct_sound_samples/cry_kango.bin"

	.align 2
Cry_Kinboxo::
	.incbin "sound/direct_sound_samples/cry_kinboxo.bin"

	.align 2
Cry_Punchzo::
	.incbin "sound/direct_sound_samples/cry_punchzo.bin"

	.align 2
Cry_Feentee::
	.incbin "sound/direct_sound_samples/cry_feentee.bin"

	.align 2
Cry_Helento::
	.incbin "sound/direct_sound_samples/cry_helento.bin"

	.align 2
Cry_Helenchoe::
	.incbin "sound/direct_sound_samples/cry_helenchoe.bin"

	.align 2
Cry_Pikish::
	.incbin "sound/direct_sound_samples/cry_pikish.bin"

	.align 2
Cry_Lionegosh::
	.incbin "sound/direct_sound_samples/cry_lionegosh.bin"

	.align 2
Cry_Jonic::
	.incbin "sound/direct_sound_samples/cry_jonic.bin"

	.align 2
Cry_Doric::
	.incbin "sound/direct_sound_samples/cry_doric.bin"

	.align 2
Cry_Corint::
	.incbin "sound/direct_sound_samples/cry_corint.bin"

	.align 2
Cry_Flachow::
	.incbin "sound/direct_sound_samples/cry_flachow.bin"

	.align 2
Cry_Furning::
	.incbin "sound/direct_sound_samples/cry_furning.bin"

	.align 2
Cry_Crabbix::
	.incbin "sound/direct_sound_samples/cry_crabbix.bin"

	.align 2
Cry_Dzoibix::
	.incbin "sound/direct_sound_samples/cry_dzoibix.bin"

	.align 2
Cry_Spingen::
	.incbin "sound/direct_sound_samples/cry_spingen.bin"

	.align 2
Cry_Duosgen::
	.incbin "sound/direct_sound_samples/cry_duosgen.bin"

	.align 2
Cry_Blahdalah::
	.incbin "sound/direct_sound_samples/cry_blahdalah.bin"

	.align 2
Cry_Bubel::
	.incbin "sound/direct_sound_samples/cry_bubel.bin"

	.align 2
Cry_Scentbird::
	.incbin "sound/direct_sound_samples/cry_scentbird.bin"

	.align 2
Cry_Norion::
	.incbin "sound/direct_sound_samples/cry_norion.bin"

	.align 2
Cry_Phantan::
	.incbin "sound/direct_sound_samples/cry_phantan.bin"

	.align 2
Cry_Salama::
	.incbin "sound/direct_sound_samples/cry_salama.bin"

	.align 2
Cry_Mantiga::
	.incbin "sound/direct_sound_samples/cry_mantiga.bin"

	.align 2
Cry_Gallum::
	.incbin "sound/direct_sound_samples/cry_gallum.bin"

	.align 2
Cry_Airdiv::
	.incbin "sound/direct_sound_samples/cry_airdiv.bin"

	.align 2
Cry_Gappy::
	.incbin "sound/direct_sound_samples/cry_gappy.bin"

	.align 2
Cry_Ninnin::
	.incbin "sound/direct_sound_samples/cry_ninnin.bin"

	.align 2
Cry_Surhorn::
	.incbin "sound/direct_sound_samples/cry_surhorn.bin"

	.align 2
Cry_Shega::
	.incbin "sound/direct_sound_samples/cry_shega.bin"

	.align 2
Cry_Zeeco::
	.incbin "sound/direct_sound_samples/cry_zeeco.bin"

	.align 2
Cry_Psirilla::
	.incbin "sound/direct_sound_samples/cry_psirilla.bin"

	.align 2
Cry_Mechrab::
	.incbin "sound/direct_sound_samples/cry_mechrab.bin"

	.align 2
Cry_Bobcrab::
	.incbin "sound/direct_sound_samples/cry_bobcrab.bin"

	.align 2
Cry_Spiki::
	.incbin "sound/direct_sound_samples/cry_spiki.bin"

	.align 2
Cry_Eliko::
	.incbin "sound/direct_sound_samples/cry_eliko.bin"

	.align 2
Cry_Sespiral::
	.incbin "sound/direct_sound_samples/cry_sespiral.bin"

	.align 2
Cry_Dendriral::
	.incbin "sound/direct_sound_samples/cry_dendriral.bin"

	.align 2
Cry_Vogoo::
	.incbin "sound/direct_sound_samples/cry_vogoo.bin"

	.align 2
Cry_Monkoodu::
	.incbin "sound/direct_sound_samples/cry_monkoodu.bin"

	.align 2
Cry_Klevalt::
	.incbin "sound/direct_sound_samples/cry_klevalt.bin"

	.align 2
Cry_Klesung::
	.incbin "sound/direct_sound_samples/cry_klesung.bin"

	.align 2
Cry_Sikedonke::
	.incbin "sound/direct_sound_samples/cry_sikedonke.bin"

	.align 2
Cry_Powergass::
	.incbin "sound/direct_sound_samples/cry_powergass.bin"

	.align 2
Cry_Pasqall::
	.incbin "sound/direct_sound_samples/cry_pasqall.bin"

	.align 2
Cry_Rocorrodo::
	.incbin "sound/direct_sound_samples/cry_rocorrodo.bin"

	.align 2
Cry_Cornodro::
	.incbin "sound/direct_sound_samples/cry_cornodro.bin"

	.align 2
Cry_Karidari::
	.incbin "sound/direct_sound_samples/cry_karidari.bin"

	.align 2
Cry_Captrunke::
	.incbin "sound/direct_sound_samples/cry_captrunke.bin"

	.align 2
Cry_Bankedon::
	.incbin "sound/direct_sound_samples/cry_bankedon.bin"

	.align 2
Cry_Plures::
	.incbin "sound/direct_sound_samples/cry_plures.bin"

	.align 2
Cry_Dracoon::
	.incbin "sound/direct_sound_samples/cry_dracoon.bin"

	.align 2
Cry_Piscy::
	.incbin "sound/direct_sound_samples/cry_piscy.bin"

	.align 2
Cry_Dolphe::
	.incbin "sound/direct_sound_samples/cry_dolphe.bin"

	.align 2
Cry_Prawby::
	.incbin "sound/direct_sound_samples/cry_prawby.bin"

	.align 2
Cry_Prawking:
	.incbin "sound/direct_sound_samples/cry_prawking.bin"

	.align 2
Cry_Bethin::
	.incbin "sound/direct_sound_samples/cry_bethin.bin"

	.align 2
Cry_Beetespuk::
	.incbin "sound/direct_sound_samples/cry_beetespuk.bin"

	.align 2
Cry_Saximaux::
	.incbin "sound/direct_sound_samples/cry_saximaux.bin"

	.align 2
Cry_Ektron::
	.incbin "sound/direct_sound_samples/cry_ektron.bin"

	.align 2
Cry_Garsoom::
	.incbin "sound/direct_sound_samples/cry_garsoom.bin"

	.align 2
Cry_Tejemeje::
	.incbin "sound/direct_sound_samples/cry_tejemeje.bin"

	.align 2
Cry_Furran::
	.incbin "sound/direct_sound_samples/cry_furran.bin"

	.align 2
Cry_Thundish::
	.incbin "sound/direct_sound_samples/cry_thundish.bin"

	.align 2
Cry_Thundran::
	.incbin "sound/direct_sound_samples/cry_thundran.bin"

	.align 2
Cry_Shacker::
	.incbin "sound/direct_sound_samples/cry_shacker.bin"

	.align 2
Cry_Eyendy::
	.incbin "sound/direct_sound_samples/cry_eyendy.bin"

	.align 2
Cry_Cwabay::
	.incbin "sound/direct_sound_samples/cry_cwabay.bin"

	.align 2
Cry_Wetway::
	.incbin "sound/direct_sound_samples/cry_wetway.bin"

	.align 2
Cry_Joylway::
	.incbin "sound/direct_sound_samples/cry_joylway.bin"

	.align 2
Cry_Heatway::
	.incbin "sound/direct_sound_samples/cry_heatway.bin"

	.align 2
Cry_Arbeluc::
	.incbin "sound/direct_sound_samples/cry_arbeluc.bin"

	.align 2
Cry_Spiraulix::
	.incbin "sound/direct_sound_samples/cry_spiraulix.bin"

	.align 2
Cry_Messaurix::
	.incbin "sound/direct_sound_samples/cry_messaurix.bin"

	.align 2
Cry_Fishix::
	.incbin "sound/direct_sound_samples/cry_fishix.bin"

	.align 2
Cry_Cefasokix::
	.incbin "sound/direct_sound_samples/cry_cefasokix.bin"

	.align 2
Cry_Beakodoron::
	.incbin "sound/direct_sound_samples/cry_beakodoron.bin"

	.align 2
Cry_Boultan::
	.incbin "sound/direct_sound_samples/cry_boultan.bin"

	.align 2
Cry_Bereuga::
	.incbin "sound/direct_sound_samples/cry_bereuga.bin"

	.align 2
Cry_Emetrik::
	.incbin "sound/direct_sound_samples/cry_emetrik.bin"

	.align 2
Cry_Paratiki::
	.incbin "sound/direct_sound_samples/cry_paratiki.bin"

	.align 2
Cry_Mithedaon::
	.incbin "sound/direct_sound_samples/cry_mithedaon.bin"

	.align 2
Cry_Whirldraon::
	.incbin "sound/direct_sound_samples/cry_whirldraon.bin"

	.align 2
Cry_Mightdra::
	.incbin "sound/direct_sound_samples/cry_mightdra.bin"

	.align 2
Cry_Zengredse::
	.incbin "sound/direct_sound_samples/cry_zengredse.bin"

	.align 2
Cry_Wiami::
	.incbin "sound/direct_sound_samples/cry_wiami.bin"

	.align 2
Cry_Potac::
	.incbin "sound/direct_sound_samples/cry_potac.bin"

	.align 2
Cry_Tubirato::
	.incbin "sound/direct_sound_samples/cry_tubirato.bin"

	.align 2
Cry_Ogritato::
	.incbin "sound/direct_sound_samples/cry_ogritato.bin"

	.align 2
Cry_Lavlon::
	.incbin "sound/direct_sound_samples/cry_lavlon.bin"

	.align 2
Cry_Magbol::
	.incbin "sound/direct_sound_samples/cry_magbol.bin"

	.align 2
Cry_Canlava::
	.incbin "sound/direct_sound_samples/cry_canlava.bin"

	.align 2
Cry_Shelldan::
	.incbin "sound/direct_sound_samples/cry_shelldan.bin"

	.align 2
Cry_Licka::
	.incbin "sound/direct_sound_samples/cry_licka.bin"

	.align 2
Cry_Tongrito::
	.incbin "sound/direct_sound_samples/cry_tongrito.bin"

	.align 2
Cry_Furbee::
	.incbin "sound/direct_sound_samples/cry_furbee.bin"

	.align 2
Cry_Morkibia::
	.incbin "sound/direct_sound_samples/cry_morkibia.bin"

	.align 2
Cry_Kiwirawa::
	.incbin "sound/direct_sound_samples/cry_kiwirawa.bin"

	.align 2
Cry_Kiawariwa::
	.incbin "sound/direct_sound_samples/cry_kiawariwa.bin"

	.align 2
Cry_Bzby::
	.incbin "sound/direct_sound_samples/cry_bzby.bin"

	.align 2
Cry_Kwimbee::
	.incbin "sound/direct_sound_samples/cry_kwimbee.bin"

	.align 2
Cry_Verpillar::
	.incbin "sound/direct_sound_samples/cry_verpillar.bin"

	.align 2
Cry_Triworm::
	.incbin "sound/direct_sound_samples/cry_triworm.bin"

	.align 2
Cry_Tostol::
	.incbin "sound/direct_sound_samples/cry_tostol.bin"

	.align 2
Cry_Eloru::
	.incbin "sound/direct_sound_samples/cry_eloru.bin"

	.align 2
Cry_Aenguile::
	.incbin "sound/direct_sound_samples/cry_aenguile.bin"

	.align 2
Cry_Gusvolts::
	.incbin "sound/direct_sound_samples/cry_gusvolts.bin"

	.align 2
Cry_Airi::
	.incbin "sound/direct_sound_samples/cry_airi.bin"

	.align 2
Cry_Fookid::
	.incbin "sound/direct_sound_samples/cry_fookid.bin"

	.align 2
Cry_Madnut::
	.incbin "sound/direct_sound_samples/cry_madnut.bin"

	.align 2
Cry_Woodird::
	.incbin "sound/direct_sound_samples/cry_woodird.bin"

	.align 2
Cry_Freion::
	.incbin "sound/direct_sound_samples/cry_freion.bin"

	.align 2
Cry_Coronneo::
	.incbin "sound/direct_sound_samples/cry_coronneo.bin"

	.align 2
Cry_Teamon::
	.incbin "sound/direct_sound_samples/cry_teamon.bin"

	.align 2
Cry_Grasspark::
	.incbin "sound/direct_sound_samples/cry_grasspark.bin"

	.align 2
Cry_Sooregat::
	.incbin "sound/direct_sound_samples/cry_sooregat.bin"

	.align 2
Cry_Frucpao::
	.incbin "sound/direct_sound_samples/cry_frucpao.bin"

	.align 2
Cry_Beavon::
	.incbin "sound/direct_sound_samples/cry_beavon.bin"

	.align 2
Cry_Umbeavella::
	.incbin "sound/direct_sound_samples/cry_umbeavella.bin"

	.align 2
Cry_Coccnuto::
	.incbin "sound/direct_sound_samples/cry_coccnuto.bin"

	.align 2
Cry_Pitdog::
	.incbin "sound/direct_sound_samples/cry_pitdog.bin"

	.align 2
Cry_Sproof::
	.incbin "sound/direct_sound_samples/cry_sproof.bin"

	.align 2
Cry_Peatoof::
	.incbin "sound/direct_sound_samples/cry_peatoof.bin"

	.align 2
Cry_Ividigi::
	.incbin "sound/direct_sound_samples/cry_ividigi.bin"

	.align 2
Cry_Bongon::
	.incbin "sound/direct_sound_samples/cry_bongon.bin"

	.align 2
Cry_Thinkower::
	.incbin "sound/direct_sound_samples/cry_thinkower.bin"

	.align 2
Cry_Flathinker::
	.incbin "sound/direct_sound_samples/cry_flathinker.bin"

	.align 2
Cry_Taermity::
	.incbin "sound/direct_sound_samples/cry_taermity.bin"

	.align 2
Cry_Racevish::
	.incbin "sound/direct_sound_samples/cry_racevish.bin"

	.align 2
Cry_Loddish::
	.incbin "sound/direct_sound_samples/cry_loddish.bin"

	.align 2
Cry_Blosway::
	.incbin "sound/direct_sound_samples/cry_blosway.bin"

	.align 2
Cry_Indinny::
	.incbin "sound/direct_sound_samples/cry_indinny.bin"

	.align 2
Cry_Tankoo::
	.incbin "sound/direct_sound_samples/cry_tankoo.bin"

	.align 2
Cry_Craprax::
	.incbin "sound/direct_sound_samples/cry_craprax.bin"

	.align 2
Cry_Magiken::
	.incbin "sound/direct_sound_samples/cry_magiken.bin"

	.align 2
Cry_Cornscript::
	.incbin "sound/direct_sound_samples/cry_cornscript.bin"

	.align 2
Cry_Medrake::
	.incbin "sound/direct_sound_samples/cry_medrake.bin"

	.align 2
Cry_Zhipo::
	.incbin "sound/direct_sound_samples/cry_zhipo.bin"

	.align 2
Cry_Moroberry::
	.incbin "sound/direct_sound_samples/cry_moroberry.bin"

	.align 2
Cry_Boongory::
	.incbin "sound/direct_sound_samples/cry_boongory.bin"

	.align 2
Cry_Bludlop::
	.incbin "sound/direct_sound_samples/cry_bludlop.bin"

	.align 2
Cry_Vamkiri::
	.incbin "sound/direct_sound_samples/cry_vamkiri.bin"

	.align 2
Cry_Shelcual::
	.incbin "sound/direct_sound_samples/cry_shelcual.bin"

	.align 2
Cry_Grecodale::
	.incbin "sound/direct_sound_samples/cry_grecodale.bin"

	.align 2
Cry_Alligrale::
	.incbin "sound/direct_sound_samples/cry_alligrale.bin"

	.align 2
Cry_Bellyo::
	.incbin "sound/direct_sound_samples/cry_bellyo.bin"

	.align 2
Cry_Drilluk::
	.incbin "sound/direct_sound_samples/cry_drilluk.bin"

	.align 2
Cry_Sangai::
	.incbin "sound/direct_sound_samples/cry_sangai.bin"

	.align 2
Cry_Betal::
	.incbin "sound/direct_sound_samples/cry_betal.bin"

	.align 2
Cry_Deemp::
	.incbin "sound/direct_sound_samples/cry_deemp.bin"

	.align 2
Cry_Trufkie::
	.incbin "sound/direct_sound_samples/cry_trufkie.bin"

	.align 2
Cry_Truffalo::
	.incbin "sound/direct_sound_samples/cry_truffalo.bin"

	.align 2
Cry_Burnco::
	.incbin "sound/direct_sound_samples/cry_burnco.bin"

	.align 2
Cry_Flameco::
	.incbin "sound/direct_sound_samples/cry_flameco.bin"

	.align 2
Cry_Hurgoose::
	.incbin "sound/direct_sound_samples/cry_hurgoose.bin"

	.align 2
Cry_Donigoni::
	.incbin "sound/direct_sound_samples/cry_donigoni.bin"

	.align 2
Cry_Flysh::
	.incbin "sound/direct_sound_samples/cry_flysh.bin"

	.align 2
Cry_Trodic::
	.incbin "sound/direct_sound_samples/cry_trodic.bin"

	.align 2
Cry_Tidalo::
	.incbin "sound/direct_sound_samples/cry_tidalo.bin"

	.align 2
Cry_Polbear::
	.incbin "sound/direct_sound_samples/cry_polbear.bin"

	.align 2
Cry_Arbatross::
	.incbin "sound/direct_sound_samples/cry_arbatross.bin"

	.align 2
Cry_Sneetchy::
	.incbin "sound/direct_sound_samples/cry_sneetchy.bin"

	.align 2
Cry_Garedar::
	.incbin "sound/direct_sound_samples/cry_garedar.bin"

	.align 2
Cry_Farizard::
	.incbin "sound/direct_sound_samples/cry_farizard.bin"

	.align 2
Cry_Dralula::
	.incbin "sound/direct_sound_samples/cry_dralula.bin"

	.align 2
Cry_Bernardog::
	.incbin "sound/direct_sound_samples/cry_bernardog.bin"

	.align 2
Cry_Rescudog::
	.incbin "sound/direct_sound_samples/cry_rescudog.bin"

	.align 2
Cry_Emrev::
	.incbin "sound/direct_sound_samples/cry_emrev.bin"

	.align 2
Cry_Grazilla::
	.incbin "sound/direct_sound_samples/cry_grazilla.bin"

	.align 2
Cry_Ninjice::
	.incbin "sound/direct_sound_samples/cry_ninjice.bin"

	.align 2
Cry_Aztakle::
	.incbin "sound/direct_sound_samples/cry_aztakle.bin"

	.align 2
Cry_Chinnakle::
	.incbin "sound/direct_sound_samples/cry_chinnakle.bin"

	.align 2
Cry_Jarximaux::
	.incbin "sound/direct_sound_samples/cry_jarximaux.bin"

	.align 2
Cry_Etod::
	.incbin "sound/direct_sound_samples/cry_etod.bin"

	.align 2
Cry_Tarsony::
	.incbin "sound/direct_sound_samples/cry_tarsony.bin"

	.align 2
Cry_Gurtan::
	.incbin "sound/direct_sound_samples/cry_gurtan.bin"

	.align 2
Cry_Conqari::
	.incbin "sound/direct_sound_samples/cry_conqari.bin"

	.align 2
Cry_Titatoad::
	.incbin "sound/direct_sound_samples/cry_titatoad.bin"

	.align 2
Cry_Titafrota::
	.incbin "sound/direct_sound_samples/cry_titafrota.bin"

	.align 2
Cry_Titallama::
	.incbin "sound/direct_sound_samples/cry_titallama.bin"

	.align 2
Cry_Crogronk::
	.incbin "sound/direct_sound_samples/cry_crogronk.bin"

	.align 2
Cry_Skankrin::
	.incbin "sound/direct_sound_samples/cry_skankrin.bin"

	.align 2
Cry_Baestalix::
	.incbin "sound/direct_sound_samples/cry_baestalix.bin"

	.align 2
Cry_Vivaczo::
	.incbin "sound/direct_sound_samples/cry_vivaczo.bin"

	.align 2
Cry_Shaddire::
	.incbin "sound/direct_sound_samples/cry_shaddire.bin"

	.align 2
Cry_Mothatura::
	.incbin "sound/direct_sound_samples/cry_mothatura.bin"

	.align 2
Cry_Mimikat::
	.incbin "sound/direct_sound_samples/cry_mimikat.bin"

	.align 2
Cry_Fairoot::
	.incbin "sound/direct_sound_samples/cry_fairoot.bin"

	.align 2
Cry_Coalchar::
	.incbin "sound/direct_sound_samples/cry_coalchar.bin"

	.align 2
Cry_PlugOink::
	.incbin "sound/direct_sound_samples/cry_plug_oink.bin"

	.align 2
Cry_Spig::
	.incbin "sound/direct_sound_samples/cry_spig.bin"

	.align 2
Cry_Guinette::
	.incbin "sound/direct_sound_samples/cry_guinette.bin"

	.align 2
Cry_Ordkip::
	.incbin "sound/direct_sound_samples/cry_ordkip.bin"

	.align 2
Cry_Boguon::
	.incbin "sound/direct_sound_samples/cry_boguon.bin"

	.align 2
Cry_Onike::
	.incbin "sound/direct_sound_samples/cry_onike.bin"

	.align 2
Cry_Whola::
	.incbin "sound/direct_sound_samples/cry_whola.bin"

	.align 2
Cry_Copykatte::
	.incbin "sound/direct_sound_samples/cry_copykatte.bin"

	.align 2
Cry_Beavy::
	.incbin "sound/direct_sound_samples/cry_beavy.bin"

	.align 2
Cry_Jackan::
	.incbin "sound/direct_sound_samples/cry_jackan.bin"

	.align 2
Cry_Lotbird::
	.incbin "sound/direct_sound_samples/cry_lotbird.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cry_unused_265.bin"

	.align 2
Cry_Reabari::
	.incbin "sound/direct_sound_samples/cry_reabari.bin"

	.align 2
Cry_Ruycantor::
	.incbin "sound/direct_sound_samples/cry_ruycantor.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cry_unused_268.bin"

	.align 2
Cry_Bounny::
	.incbin "sound/direct_sound_samples/cry_bounny.bin"

	.align 2
Cry_Firegg::
	.incbin "sound/direct_sound_samples/cry_firegg.bin"

	.align 2
Cry_Embaby::
	.incbin "sound/direct_sound_samples/cry_embaby.bin"

	.align 2
Cry_Tyradino::
	.incbin "sound/direct_sound_samples/cry_tyradino.bin"

	.align 2
Cry_Seegg::
	.incbin "sound/direct_sound_samples/cry_seegg.bin"

	.align 2
Cry_Flowaby::
	.incbin "sound/direct_sound_samples/cry_flowaby.bin"

	.align 2
Cry_Jardino::
	.incbin "sound/direct_sound_samples/cry_jardino.bin"

	.align 2
Cry_Aquegg::
	.incbin "sound/direct_sound_samples/cry_aquegg.bin"

	.align 2
Cry_Ornaby::
	.incbin "sound/direct_sound_samples/cry_ornaby.bin"

	.align 2
Cry_Oceadino::
	.incbin "sound/direct_sound_samples/cry_oceadino.bin"

	.align 2
Cry_Pelichen::
	.incbin "sound/direct_sound_samples/cry_pelichen.bin"

	.align 2
Cry_Bolichano::
	.incbin "sound/direct_sound_samples/cry_bolichano.bin"

	.align 2
Cry_Mazalon::
	.incbin "sound/direct_sound_samples/cry_mazalon.bin"

	.align 2
Cry_Catalon::
	.incbin "sound/direct_sound_samples/cry_catalon.bin"

	.align 2
Cry_Weedo::
	.incbin "sound/direct_sound_samples/cry_weedo.bin"

	.align 2
Cry_Flosea::
	.incbin "sound/direct_sound_samples/cry_flosea.bin"

	.align 2
Cry_Weedalgu::
	.incbin "sound/direct_sound_samples/cry_weedalgu.bin"

	.align 2
Cry_Cactino::
	.incbin "sound/direct_sound_samples/cry_cactino.bin"

	.align 2
Cry_Cacutu::
	.incbin "sound/direct_sound_samples/cry_cacutu.bin"

	.align 2
Cry_Dessertea::
	.incbin "sound/direct_sound_samples/cry_dessertea.bin"

	.align 2
Cry_Awhol::
	.incbin "sound/direct_sound_samples/cry_awhol.bin"

	.align 2
Cry_Larvly::
	.incbin "sound/direct_sound_samples/cry_larvly.bin"

	.align 2
Cry_Cricoon::
	.incbin "sound/direct_sound_samples/cry_cricoon.bin"

	.align 2
Cry_Cricrit::
	.incbin "sound/direct_sound_samples/cry_cricrit.bin"

	.align 2
Cry_Composcoon::
	.incbin "sound/direct_sound_samples/cry_composcoon.bin"

	.align 2
Cry_Flynfly::
	.incbin "sound/direct_sound_samples/cry_flynfly.bin"

	.align 2
Cry_Hamet::
	.incbin "sound/direct_sound_samples/cry_hamet.bin"

	.align 2
Cry_Ratelo::
	.incbin "sound/direct_sound_samples/cry_ratelo.bin"

	.align 2
Cry_Psimouse::
	.incbin "sound/direct_sound_samples/cry_psimouse.bin"

	.align 2
Cry_Ronslept::
	.incbin "sound/direct_sound_samples/cry_ronslept.bin"

	.align 2
Cry_Leirao::
	.incbin "sound/direct_sound_samples/cry_leirao.bin"

	.align 2
Cry_Dorliron::
	.incbin "sound/direct_sound_samples/cry_dorliron.bin"

	.align 2
Cry_Gustano::
	.incbin "sound/direct_sound_samples/cry_gustano.bin"

	.align 2
Cry_Duostano::
	.incbin "sound/direct_sound_samples/cry_duostano.bin"

	.align 2
Cry_Phico::
	.incbin "sound/direct_sound_samples/cry_phico.bin"

	.align 2
Cry_Energiz::
	.incbin "sound/direct_sound_samples/cry_energiz.bin"

	.align 2
Cry_Musclelc::
	.incbin "sound/direct_sound_samples/cry_musclelc.bin"

	.align 2
Cry_Deprip::
	.incbin "sound/direct_sound_samples/cry_deprip.bin"

	.align 2
Cry_Bobeguin::
	.incbin "sound/direct_sound_samples/cry_bobeguin.bin"

	.align 2
Cry_Amede::
	.incbin "sound/direct_sound_samples/cry_amede.bin"

	.align 2
Cry_Amedi::
	.incbin "sound/direct_sound_samples/cry_amedi.bin"

	.align 2
Cry_Hovebug::
	.incbin "sound/direct_sound_samples/cry_hovebug.bin"

	.align 2
Cry_Planebug::
	.incbin "sound/direct_sound_samples/cry_planebug.bin"

	.align 2
Cry_Babos::
	.incbin "sound/direct_sound_samples/cry_babos.bin"

	.align 2
Cry_Osoe::
	.incbin "sound/direct_sound_samples/cry_osoe.bin"

	.align 2
Cry_Simpleon::
	.incbin "sound/direct_sound_samples/cry_simpleon.bin"

	.align 2
Cry_Dobleon::
	.incbin "sound/direct_sound_samples/cry_dobleon.bin"

	.align 2
Cry_Llamayama::
	.incbin "sound/direct_sound_samples/cry_llamayama.bin"

	.align 2
Cry_Chimneyama::
	.incbin "sound/direct_sound_samples/cry_chimneyama.bin"

	.align 2
Cry_Soie::
	.incbin "sound/direct_sound_samples/cry_soie.bin"

	.align 2
Cry_Corongori::
	.incbin "sound/direct_sound_samples/cry_corongori.bin"

	.align 2
Cry_Searoket::
	.incbin "sound/direct_sound_samples/cry_searoket.bin"

	.align 2
Cry_Helixet::
	.incbin "sound/direct_sound_samples/cry_helixet.bin"

	.align 2
Cry_Tigat::
	.incbin "sound/direct_sound_samples/cry_tigat.bin"

	.align 2
Cry_Tigator::
	.incbin "sound/direct_sound_samples/cry_tigator.bin"

	.align 2
Cry_Progon::
	.incbin "sound/direct_sound_samples/cry_progon.bin"

	.align 2
Cry_Rubygon::
	.incbin "sound/direct_sound_samples/cry_rubygon.bin"

	.align 2
Cry_Saphiregon::
	.incbin "sound/direct_sound_samples/cry_saphiregon.bin"

	.align 2
Cry_Apinep::
	.incbin "sound/direct_sound_samples/cry_apinep.bin"

	.align 2
Cry_Pinark::
	.incbin "sound/direct_sound_samples/cry_pinark.bin"

	.align 2
Cry_Goduck::
	.incbin "sound/direct_sound_samples/cry_goduck.bin"

	.align 2
Cry_Dukamid::
	.incbin "sound/direct_sound_samples/cry_dukamid.bin"

	.align 2
Cry_Clostar::
	.incbin "sound/direct_sound_samples/cry_clostar.bin"

	.align 2
Cry_Stargo::
	.incbin "sound/direct_sound_samples/cry_stargo.bin"

	.align 2
Cry_Icish::
	.incbin "sound/direct_sound_samples/cry_icish.bin"

	.align 2
Cry_Freech::
	.incbin "sound/direct_sound_samples/cry_freech.bin"

	.align 2
Cry_Agoir::
	.incbin "sound/direct_sound_samples/cry_agoir.bin"

	.align 2
Cry_Mindum::
	.incbin "sound/direct_sound_samples/cry_mindum.bin"

	.align 2
Cry_Minadoom::
	.incbin "sound/direct_sound_samples/cry_minadoom.bin"

	.align 2
Cry_Coldchick::
	.incbin "sound/direct_sound_samples/cry_coldchick.bin"

	.align 2
Cry_Freezock::
	.incbin "sound/direct_sound_samples/cry_freezock.bin"

	.align 2
Cry_Cottoster::
	.incbin "sound/direct_sound_samples/cry_cottoster.bin"

	.align 2
Cry_Berchi::
	.incbin "sound/direct_sound_samples/cry_berchi.bin"

	.align 2
Cry_Mejiyonson::
	.incbin "sound/direct_sound_samples/cry_mejiyonson.bin"

	.align 2
Cry_Loapa::
	.incbin "sound/direct_sound_samples/cry_loapa.bin"

	.align 2
Cry_Torido::
	.incbin "sound/direct_sound_samples/cry_torido.bin"

	.align 2
Cry_Dotori::
	.incbin "sound/direct_sound_samples/cry_dotori.bin"

	.align 2
Cry_Enyendrode::
	.incbin "sound/direct_sound_samples/cry_enyendrode.bin"

	.align 2
Cry_Mongostre::
	.incbin "sound/direct_sound_samples/cry_mongostre.bin"

	.align 2
Cry_Tenry::
	.incbin "sound/direct_sound_samples/cry_tenry.bin"

	.align 2
Cry_Wrestoro::
	.incbin "sound/direct_sound_samples/cry_wrestoro.bin"

	.align 2
Cry_Wrestmilk::
	.incbin "sound/direct_sound_samples/cry_wrestmilk.bin"

	.align 2
Cry_Dristal::
	.incbin "sound/direct_sound_samples/cry_dristal.bin"

	.align 2
Cry_Feegon::
	.incbin "sound/direct_sound_samples/cry_feegon.bin"

	.align 2
Cry_Molebas::
	.incbin "sound/direct_sound_samples/cry_molebas.bin"

	.align 2
Cry_Dugobas::
	.incbin "sound/direct_sound_samples/cry_dugobas.bin"

	.align 2
Cry_Lapibas::
	.incbin "sound/direct_sound_samples/cry_lapibas.bin"

	.align 2
Cry_Kotokabe::
	.incbin "sound/direct_sound_samples/cry_kotokabe.bin"

	.align 2
Cry_Armay::
	.incbin "sound/direct_sound_samples/cry_armay.bin"

	.align 2
Cry_Armstorm::
	.incbin "sound/direct_sound_samples/cry_armstorm.bin"

	.align 2
Cry_Sever::
	.incbin "sound/direct_sound_samples/cry_sever.bin"

	.align 2
Cry_Ayewiraz::
	.incbin "sound/direct_sound_samples/cry_ayewiraz.bin"

	.align 2
Cry_Woopet::
	.incbin "sound/direct_sound_samples/cry_woopet.bin"

	.align 2
Cry_Fatube::
	.incbin "sound/direct_sound_samples/cry_fatube.bin"

	.align 2
Cry_Hooley::
	.incbin "sound/direct_sound_samples/cry_hooley.bin"

	.align 2
Cry_Opail::
	.incbin "sound/direct_sound_samples/cry_opail.bin"

	.align 2
Cry_Hompalon::
	.incbin "sound/direct_sound_samples/cry_hompalon.bin"

	.align 2
Cry_Gemmal::
	.incbin "sound/direct_sound_samples/cry_gemmal.bin"

	.align 2
Cry_Monkoor::
	.incbin "sound/direct_sound_samples/cry_monkoor.bin"

	.align 2
Cry_Tincrab::
	.incbin "sound/direct_sound_samples/cry_tincrab.bin"

	.align 2
Cry_Kaosune::
	.incbin "sound/direct_sound_samples/cry_kaosune.bin"

	.align 2
Cry_Kaomare::
	.incbin "sound/direct_sound_samples/cry_kaomare.bin"

	.align 2
Cry_Peezgal::
	.incbin "sound/direct_sound_samples/cry_peezgal.bin"

	.align 2
Cry_Drahago::
	.incbin "sound/direct_sound_samples/cry_drahago.bin"

	.align 2
Cry_Dendrock::
	.incbin "sound/direct_sound_samples/cry_dendrock.bin"

	.align 2
Cry_Strawbaya::
	.incbin "sound/direct_sound_samples/cry_strawbaya.bin"

	.align 2
Cry_Acornel::
	.incbin "sound/direct_sound_samples/cry_acornel.bin"

	.align 2
Cry_Liofang::
	.incbin "sound/direct_sound_samples/cry_liofang.bin"

	.align 2
Cry_Colossio::
	.incbin "sound/direct_sound_samples/cry_colossio.bin"

	.align 2
Cry_Squirriti::
	.incbin "sound/direct_sound_samples/cry_squirriti.bin"

	.align 2
Cry_Iguagon::
	.incbin "sound/direct_sound_samples/cry_iguagon.bin"

	.align 2
Cry_Balagon::
	.incbin "sound/direct_sound_samples/cry_balagon.bin"

	.align 2
Cry_Descomune::
	.incbin "sound/direct_sound_samples/cry_descomune.bin"

	.align 2
Cry_Tynigon::
	.incbin "sound/direct_sound_samples/cry_tynigon.bin"

	.align 2
Cry_Spinwing::
	.incbin "sound/direct_sound_samples/cry_spinwing.bin"

	.align 2
Cry_Tanord::
	.incbin "sound/direct_sound_samples/cry_tanord.bin"

	.align 2
Cry_Karendi::
	.incbin "sound/direct_sound_samples/cry_karendi.bin"

	.align 2
Cry_Garotao::
	.incbin "sound/direct_sound_samples/cry_garotao.bin"

	.align 2
Cry_Gritespec::
	.incbin "sound/direct_sound_samples/cry_gritespec.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
