RustboroCity_House2_MapScripts:: @ 8215EB3
	.byte 0

RustboroCity_House2_EventScript_PokefanF:: @ 8215EB4
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl:: @ 8215EBD
	msgbox RustboroCity_House2_Text_BettiKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent: @ 8215EC6
	.string "The TRAINER'S SCHOOL is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a GYM LEADER.$"

RustboroCity_House2_Text_BettiKnowsALot: @ 8215F21
	.string "BETTI, the GYM LEADER, really knows\n"
	.string "a lot about POKéMON.\p"
	.string "She's really strong, too!$"

